theory 
  ontologies
imports
  "CENELEC_50128/CENELEC_50128"
  "Conceptual/Conceptual"
  "mathex/mathex"
  "math_paper/math_paper"
  "scholarly_paper/scholarly_paper"
  "small_math/small_math"
  "technical_report/technical_report"
begin
end
