#!/usr/bin/env bash
# A simple build script for compiling the DOF LateX-to-LaTeX
# translator into an executable jar-archive.
#
# Note that this setup is not designed with to goal of being a good
# template for Scala projects in general. This setup is designed with
# the main (and only) goal of not requiring any dependencies that are
# not already provided by a standard Isabelle installation. Hence, we
# rely on the Scala compiler and runtime provided by Isabelle and use
# bash-scripts for compilation.
#

ISABELLE=${1:-`which isabelle`}
ISABELLE_VERSION=`$ISABELLE version`
SCALAC_VERSION=`$ISABELLE scalac -version`

echo "Building dof_latex_converter using"
echo " * $ISABELLE_VERSION"
echo " * $SCALAC_VERSION"
$ISABELLE scalac src/dof_latex_converter.scala -d bin/dof_latex_converter.jar
