#!/usr/bin/env bash
# Copyright (c) 2018 The University of Sheffield. All rights reserved.
#               2018 The University of Paris-Sud. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# SPDX-License-Identifier: BSD-2-Clause


ISABELLE=${1:-`which isabelle`}
export `$ISABELLE getenv ISABELLE_HOME_USER`
export `$ISABELLE getenv ISABELLE_TOOLS`

if [[ -d "$ISABELLE_HOME_USER/DOF" ]]; then
    echo "Moving old installation to $DIR/settings $ISABELLE_HOME_USER/DOF.bak"
    rm -rf "$ISABELLE_HOME_USER/DOF.bak"
    mv "$ISABELLE_HOME_USER/DOF" "$ISABELLE_HOME_USER/DOF.bak"
fi

DIR="$ISABELLE_HOME_USER/DOF/Tools"
echo "Installing Tools in $DIR"
mkdir -p "$DIR"
cp Tools/* "$DIR"
chmod 755 "$DIR"/*

# Register Tools
DIR="$ISABELLE_HOME_USER/etc"
mkdir -p "$DIR"
if [[ $ISABELLE_TOOLS = *DOF* ]]; then
    echo "Tools already registered in $DIR/settings"
else
    echo 'ISABELLE_TOOLS=$ISABELLE_TOOLS:$ISABELLE_HOME_USER/DOF/Tools' \
         >> "$DIR/settings"
    echo "Registering tools in Tools already registered in $DIR/settings"
fi


# Build Scala lib
(cd converter; ./build $ISABELLE)
DIR="$ISABELLE_HOME_USER/DOF/lib"
echo "Installing library in $DIR"
mkdir -p "$DIR" 
cp converter/bin/*.jar "$DIR"

VERSION=`$ISABELLE scala converter/bin/*.jar -v`

DIR="$ISABELLE_HOME_USER/DOF/document-template"
echo "Installing document templates in $DIR"
mkdir -p "$DIR"
cp document-template/* "$DIR"
sed -i -e "s/<VERSION>/$VERSION/" "$DIR"/build


DIR="$ISABELLE_HOME_USER/DOF/latex"
echo "Installing LaTeX styles in $DIR"
mkdir -p "$DIR"
cp latex/*.sty "$DIR"

echo "Installation of $VERSION successful."
